template_name: "连携模板-优先支援"
handlers:
  - states: "[按键可用-连携技]"
    sub_states:
      - states: "[连携技-1-支援]"
        operations:
          - op_name: "按键-连携技-左"
            data: []
          - op_name: "等待秒数"
            data: [ "1.5" ]
      - states: "[连携技-2-支援]"
        operations:
          - op_name: "按键-连携技-右"
            data: []
          - op_name: "等待秒数"
            data: [ "1.5" ]
      - states: ""
        operations:
          - op_name: "按键-连携技-右"
            data: []
          - op_name: "等待秒数"
            data: [ "1.5" ]
