template_name: "站场模板-强攻站场"
handlers:
  - states: "[前台-强攻]"
    sub_states:
      - state_template: "站场模板-全角色"
  - states: "[前台-击破] | [前台-支援] | [前台-异常] | [前台-防护]"
    operations:
      - op_name: "按键-切换角色-下一个"
        data: []
      - op_name: "等待秒数"
        data: [ "0.5" ]
