template_name: "站场模板-安比"
handlers:
  - states: "[按键可用-终结技]"
    operations:
      - op_name: "按键-终结技"
        data: []
      - op_name: "等待秒数"
        data: [ "3" ]
  - states: "[按键可用-特殊攻击]"
    operations:
      - operation_template: "安比-3A特殊攻击"
  - states: ""
    operations:
      - operation_template: "安比-3A重击"
