template_name: "切换角色模板-强攻优先"
handlers:
- states: "[后台-2-强攻]"
  operations:
    - op_name: "按键-切换角色-上一个"
      data: [ ]
    - op_name: "等待秒数"
      data: [ "0.2" ]
    - op_name: "按键-普通攻击"
      data: [ ]
- states: ""
  operations:
    - op_name: "按键-切换角色-下一个"
      data: [ ]
    - op_name: "等待秒数"
      data: [ "0.2" ]
    - op_name: "按键-普通攻击"
      data: [ ]