template_name: "站场模板-未识别角色"
handlers:
- states: "![前台-击破] & ![前台-强攻] & ![前台-支援] & ![前台-防护] & ![前台-异常]"
  sub_states:
  - states: "[按键可用-终结技]"
    operations:
      - op_name: "按键-终结技"
        data: []
      - op_name: "等待秒数"
        data: [ "3" ]
  - states: "[按键可用-特殊攻击]"
    operations:
      - op_name: "按键-特殊攻击"
        data: []
      - op_name: "等待秒数"
        data: [ "0.3" ]
  - states: ""
    operations:
      - op_name: "按键-普通攻击"
        data: []
      - op_name: "等待秒数"
        data: [ "0.3" ]