handlers:
  - states: "[前台-青衣]"
    sub_states:

    - states: "![自定义-开始充电, 0, 10]"
      operations:
        - op_name: "设置状态"
          data: [ "自定义-开始充电", "0", "1" ]

    - states: "[自定义-开始充电, 6, 10]"
      operations:
        - op_name: "清除状态"
          data: [ "自定义-开始充电" ]
        - operation_template: "青衣-重击"

    - states: "[按键可用-特殊攻击]"
      operations:
        - op_name: "按键-闪避"
          data: [ ]
        - op_name: "等待秒数"
          data: [ "0.1" ]
        - op_name: "按键-特殊攻击"
          data: [ ]
        - op_name: "等待秒数"
          data: [ "1" ]

    - states: ""
      operations:
        - operation_template: "青衣-平A"
