project_name: "ZenlessZoneZero-OneDragon"
win_title: "ZenlessZoneZero"
python_version: "3.11.9"
github_repository: "github.com/DoctorReid/ZenlessZoneZero-OneDragon.git"
gitee_repository: ""
project_git_branch: "main"
requirements: "requirements-prod.txt"
screen_standard_width: 1920
screen_standard_height: 1080
