name: "切换角色-上一个"
scenes:
- triggers: ["闪避识别-黄光", "闪避识别-红光"]
  handlers:
  - states: "( [闪避识别-黄光, 0, 1] | [闪避识别-红光, 0, 1] ) & ![按键-切换角色-上一个, 0, 1]"
    operations:
      - op_name: "按键-切换角色-上一个"
        data: []
      - op_name: "等待秒数"
        data: ["0.01"]
      - op_name: "按键-普通攻击"
        data: []
