name: "击破站场-强攻速切"
allow_ultimate:
  - agent_type: "强攻"

scenes:

- triggers: ["闪避识别-黄光", "闪避识别-红光"]
  interval: 0.5
  handlers:
  - states: "( [闪避识别-黄光, 0, 1] | [闪避识别-红光, 0, 1] ) & ![按键-闪避, 0, 1]"
    operations:
      - op_name: "按键-闪避"
        data: []
      - op_name: "等待秒数"
        data: ["0.01"]
      - op_name: "按键-普通攻击"
        data: []

- triggers: ["按键可用-快速支援"]
  interval: 1
  handlers:
  - states: "[按键可用-快速支援]"
    operations:
      - op_name: "按键-切换角色-下一个"
        data: []
      - op_name: "等待秒数"
        data: [ "0.5" ]

- triggers: ["按键可用-连携技"]
  interval: 1
  handlers:
  - state_template: "连携模板-优先支援"

- triggers: []
  interval: 0.5
  handlers:
  - states: "[按键-连携技-左, 0, 10] | [按键-连携技-右, 0, 10]"
    sub_states:
      - state_template: "站场模板-强攻站场"
  - state_template: "站场模板-击破站场"
