allow_ultimate:
  - agent_type: "强攻"

scenes:

  - triggers: [ "闪避识别-黄光", "闪避识别-红光" ]
    interval: 1
    handlers:
      - states: "[闪避识别-黄光]"
        sub_states:
          - state_template: "双反模板-强攻"
          - state_template: "双反模板-击破"
          - state_template: "双反模板-下一个"
      - states: "[闪避识别-红光]"
        sub_states:
          - state_template: "闪A模板-全角色"

  - triggers: [ "按键可用-快速支援" ]
    interval: 1
    handlers:
      - states: "[按键可用-快速支援]"
        operations:
          - op_name: "按键-切换角色-下一个"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.5" ]

  - triggers: [ "按键可用-连携技" ]
    interval: 1
    handlers:
      - states: "[按键可用-连携技]"
        sub_states:
          - state_template: "连携模板-支援"
          - state_template: "连携模板-强攻"
          - state_template: "连携模板-击破"
          - state_template: "连携模板-防护"
          - state_template: "连携模板-异常"
          - state_template: "连携模板-跳过"

  - triggers: [ ]
    interval: 0.5
    handlers:
      # 刚开始未识别到角色时候不要乱切
      - state_template: "站场模板-未识别角色"
      - states: "[按键-连携技-左, 0, 12] | [按键-连携技-右, 0, 12]"
        sub_states:
          - state_template: "站场模板-强攻站场"
      - state_template: "站场模板-击破站场"
