allow_ultimate:
  - agent_type: "强攻"

scenes:

- triggers: ["闪避识别-黄光", "闪避识别-红光"]
  interval: 1
  handlers:
  - states: "[闪避识别-黄光, 0, 1] & [后台-2-强攻]"
    operations:
      - op_name: "按键-切换角色-上一个"
        data: []
      - op_name: "等待秒数"
        data: [ "0.2" ]
      - op_name: "按键-普通攻击"
        data: []
  - states: "[闪避识别-黄光, 0, 1]"
    operations:
      - op_name: "按键-切换角色-下一个"
        data: []
      - op_name: "等待秒数"
        data: [ "0.2" ]
      - op_name: "按键-普通攻击"
        data: []
  - states: "[闪避识别-红光, 0, 1]"
    operations:
      - op_name: "按键-闪避"
        data: []
      - op_name: "等待秒数"
        data: [ "0.2" ]
      - op_name: "按键-普通攻击"
        data: []

- triggers: ["按键可用-快速支援"]
  interval: 1
  handlers:
  - states: "[按键可用-快速支援]"
    operations:
    - op_name: "按键-切换角色-下一个"
      data: []
    - op_name: "等待秒数"
      data: [ "0.5" ]

- triggers: ["按键可用-连携技"]
  interval: 1
  handlers:
  - state_template: "连携模板-支援"

- triggers: []
  interval: 1
  handlers:
  - states: "[按键-连携技-左, 0, 12] | [按键-连携技-右, 0, 12]"
    sub_states:
    - states: "[前台-朱鸢]"
      sub_states:
      - states: "[按键可用-终结技]"
        operations:
          - op_name: "按键-终结技"
            data: []
      - states: "[按键可用-特殊攻击]"
        operations:
          - op_name: "按键-特殊攻击"
            data: []
      - states: ""
        operations:
          - op_name: "按键-普通攻击-按下"
            data: [ "1" ]
    - states: ""
      operations:
      - op_name: "按键-切换角色-下一个"
        data: []
  - state_template: "站场模板-击破站场"