name: "鲨鱼站场"
allow_ultimate:
  - agent_type: "强攻"

scenes:

- triggers: ["闪避识别-黄光", "闪避识别-红光"]
  interval: 0.5
  handlers:
  - states: "[闪避识别-黄光, 0, 1]"
    sub_states:
      - state_template: "自动战斗黄光模板-全角色"
  - states: "[闪避识别-红光, 0, 1]"
    sub_states:
      - state_template: "自动战斗闪避模板-全角色"

- triggers: ["按键可用-快速支援"]
  interval: 1
  handlers:
  - states: "[按键可用-快速支援]"
    operations:
      - op_name: "按键-切换角色-下一个"
        data: []
      - op_name: "等待秒数"
        data: [ "0.1" ]

# 狼哥第一次触发，先支援、再强攻；艾莲第一次触发，先支援、再强攻；苍角不太会触发
- triggers: ["按键可用-连携技"]
  interval: 1
  handlers:
  - states: "[按键可用-连携技]"
    sub_states:
      - state_template: "连携模板-支援"
      - state_template: "连携模板-强攻"
      - state_template: "连携模板-跳过"

# TODO： 测下来，有时鲨鱼似乎会被击破或支援前台触发扔了个e立马切人了
- triggers: ["前台-击破"]
  interval: 0.7
  handlers:
  - state_template: "击破速切模板-全角色"

- triggers: ["前台-支援"]
  interval: 0.7
  handlers:
  - state_template: "支援速切模板-全角色"

- triggers: []
  interval: 0.35
  handlers:
    - states: "[前台-艾莲]"
      sub_states:
      - states: "([按键-连携技-左, 0, 10] | [按键-连携技-右, 0, 10]) & [按键可用-终结技]"
        operations:
          - op_name: "按键-闪避"
            data: []
          - op_name: "等待秒数"
            data: [ "0.1" ]
          - op_name: "按键-终结技"
            data: []

      - states: "([按键-连携技-左, 0, 10] | [按键-连携技-右, 0, 10]) & [按键可用-特殊攻击]"
        operations:
          - op_name: "按键-闪避"
            data: []
          - op_name: "等待秒数"
            data: [ "0.1" ]

          # 第一次 ea
          - op_name: "按键-特殊攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          # 再按一次e防止没按到
          - op_name: "按键-特殊攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          # 接第3段a；不停a，防止e没按出来待在原地
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

          # 第二次 ea
          - op_name: "按键-特殊攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          # 再按一次e防止没按到
          - op_name: "按键-特殊攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          # 接第3段a；不停a，防止e没按出来待在原地
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]
          - op_name: "按键-普通攻击"
            data: [ ]
          - op_name: "等待秒数"
            data: [ "0.2" ]

#          # ea，不稳定
#          - op_name: "按键-特殊攻击"
#            data: []
#          - op_name: "等待秒数"
#            data: [ "1.5" ]
#          - op_name: "按键-普通攻击-按下"
#            data: [ "1.5" ]
#          - op_name: "等待秒数"
#            data: [ "0.2" ]

      - states: ""
        operations:
          - op_name: "按键-移动-前-按下"
            data: ["0.1"]
          - op_name: "按键-移动-前-按下"
            data: []
          - op_name: "按键-闪避-按下"
            data: ["0.3"]
          - op_name: "按键-普通攻击-按下"
            data: ["1.2"]
          - op_name: "按键-移动-前-松开"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.1"]
          - op_name: "按键-闪避-按下"
            data: ["0.1"]
          - op_name: "按键-移动-前-按下"
            data: ["0.1"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.5"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.5"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.5"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
          - op_name: "按键-普通攻击"
            data: []
          - op_name: "按键-移动-前-按下"
            data: ["0.2"]
